services:
  app:
    image: 'marketplace'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ac
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/marketplace2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1212
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "6868:8080"
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1212
      - POSTGRES_DB=marketplace2
    ports:
      - "5433:5432"
